import { buildContextBundle } from "../contextBundle.js";
import type { ClaimedJob, JobHandlerResult } from "../types.js";

function buildStubContent(job: ClaimedJob): string {
  const context = buildContextBundle(job);
  const promptLine = context.userPrompt
    ? `- Regeneration note: ${context.userPrompt}`
    : "- Regeneration note: none";
  const descriptionLine = context.ticketDescription
    ? `- Ticket description: ${context.ticketDescription}`
    : "- Ticket description: none";
  const btcaLine = context.btcaProjectId
    ? `- BTCA project: ${context.btcaProjectId}`
    : "- BTCA project: not configured";

  return [
    "# Acceptance Criteria",
    "",
    "> Generated by the deterministic worker stub with Phase 6-ready context.",
    "",
    "## Ticket Context",
    `- Ticket title: ${context.ticketTitle}`,
    descriptionLine,
    `- Ticket type: ${context.ticketType}`,
    `- Git remote: ${context.gitRemoteUrl ?? "not configured"}`,
    `- Default branch: ${context.defaultBranch ?? "not configured"}`,
    btcaLine,
    "",
    "## Scenario 1: Ticket is ready for review",
    "- Given a queued GENERATE_AC job exists for this ticket",
    "- When the worker claims and completes the job",
    "- Then a draft AC artifact is created or updated for the ticket",
    "",
    "## Scenario 2: Job metadata is preserved",
    `- Given job ${context.jobId} is processing attempt ${context.attempt}`,
    "- When the worker returns a successful result payload",
    "- Then the job result is stored and visible in the ticket detail UI",
    "",
    "## Scenario 3: Prompt context is surfaced",
    promptLine,
  ].join("\n");
}

export async function handleGenerateAc(job: ClaimedJob): Promise<JobHandlerResult> {
  // Phase 5 stub:
  // Replace this deterministic payload generator with the real AC pipeline in
  // Phase 6. The future implementation should build a bounded prompt from the
  // ticket context, optionally query BTCA for grounded repo context, invoke
  // Forge/Muse, and return the generated markdown as `result.content`.
  return {
    status: "succeeded",
    result: {
      content: buildStubContent(job),
    },
  };
}
