import { useState } from "react";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../../convex/_generated/api";
import { Id } from "../../../convex/_generated/dataModel";
import { TicketStatus, ArtifactType } from "../../../convex/schema";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Textarea } from "@/components/ui/textarea";
import { FileText, CheckCircle, RotateCcw, XCircle, FileClock, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface ArtifactPanelProps {
  ticketId: Id<"tickets">;
  selectedPhase: TicketStatus;
  currentTicketPhase: TicketStatus;
}

const PHASE_TO_ARTIFACT: Partial<Record<TicketStatus, ArtifactType>> = {
  TEST_CASE: "AC",
  PLANNING: "PLAN",
  CODE_GENERATION: "CODE",
};

export function ArtifactPanel({ ticketId, selectedPhase, currentTicketPhase }: ArtifactPanelProps) {
  const artifacts = useQuery(api.artifacts.getTicketArtifacts, { ticketId });
  const approveArtifact = useMutation(api.artifacts.approveArtifact);
  const unapproveArtifact = useMutation(api.artifacts.unapproveArtifact);
  const requestRegeneration = useMutation(api.workflowEngine.requestRegeneration);

  const [promptInput, setPromptInput] = useState("");
  const [isRegenerating, setIsRegenerating] = useState(false);

  // Determine what type of artifact we should be showing based on the selected phase
  const expectedArtifactType = PHASE_TO_ARTIFACT[selectedPhase];

  if (artifacts === undefined) {
    return (
      <div className="w-full h-[500px] flex items-center justify-center border rounded-xl bg-card/50">
        <p className="text-muted-foreground animate-pulse">Loading artifact...</p>
      </div>
    );
  }

  const activeArtifact = expectedArtifactType
    ? artifacts.find(a => a.type === expectedArtifactType)
    : undefined;

  // Phase does not have an artifact attached to it (e.g., BACKLOG, COMPLETED)
  if (!expectedArtifactType) {
    return (
      <div className="w-full h-[500px] flex flex-col items-center justify-center border rounded-xl bg-card border-dashed gap-4">
        <div className="bg-muted p-4 rounded-full">
          <FileClock className="w-8 h-8 text-muted-foreground" />
        </div>
        <div className="flex flex-col gap-2 items-center">
          <h2 className="text-xl font-semibold text-foreground tracking-tight">No Artifact Required</h2>
          <p className="text-muted-foreground text-center max-w-sm">
            The phase <span className="font-medium text-foreground">{selectedPhase}</span> does not produce a versioned document.
          </p>
        </div>
      </div>
    );
  }

  const handleApprove = async () => {
    if (!activeArtifact) return;
    try {
      await approveArtifact({ artifactId: activeArtifact._id });
      toast.success("Artifact approved!");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to approve artifact");
    }
  };

  const handleUnapprove = async () => {
    if (!activeArtifact) return;
    try {
      await unapproveArtifact({ artifactId: activeArtifact._id });
      toast.info("Status reverted to Draft.");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to revert artifact status");
    }
  };

  const handleRegenerate = async () => {
    setIsRegenerating(true);
    try {
      await requestRegeneration({
        ticketId,
        phase: selectedPhase,
        userPrompt: promptInput,
      });
      toast.success("Regeneration task queued successfully!");
      setPromptInput("");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to queue regeneration task");
    } finally {
      setIsRegenerating(false);
    }
  };

  const isCurrentPhase = selectedPhase === currentTicketPhase;

  return (
    <div className="flex flex-col h-[600px] border rounded-xl bg-card overflow-hidden shadow-sm">
      {/* Header Bar */}
      <div className="bg-muted/30 border-b px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-primary/10 p-2 rounded-md">
            <FileText className="w-5 h-5 text-primary" />
          </div>
          <div className="flex flex-col">
            <h2 className="text-lg font-semibold tracking-tight">
              {expectedArtifactType} Document
            </h2>
            <p className="text-xs text-muted-foreground">
              Generated by AI Forge Pipeline
            </p>
          </div>
        </div>

        {activeArtifact && (
          <Badge
            variant={activeArtifact.status === "approved" ? "secondary" : "secondary"}
            className={`px-2.5 py-0.5 text-xs font-medium uppercase tracking-wider ${activeArtifact.status === "approved" ? "bg-emerald-100 text-emerald-800 hover:bg-emerald-200 border-transparent" : ""}`}
          >
            {activeArtifact.status}
          </Badge>
        )}
      </div>

      {/* Editor / Content Box */}
      <div className="flex-1 overflow-y-auto p-6 bg-background/50">
        {activeArtifact ? (
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <pre className="whitespace-pre-wrap font-mono text-[13px] leading-relaxed bg-transparent p-0 m-0 border-none outline-none">
              {activeArtifact.content}
            </pre>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full text-center gap-4">
            <div className="relative">
              <FileText className="w-12 h-12 text-muted/30" />
              {isCurrentPhase && (
                <div className="absolute -bottom-2 -right-2 bg-background rounded-full p-1 border shadow-sm">
                  <Loader2 className="w-4 h-4 text-primary animate-spin" />
                </div>
              )}
            </div>
            <div className="flex flex-col gap-1 items-center">
              <p className="text-lg font-medium text-foreground">Waiting for Content</p>
              <p className="text-sm text-muted-foreground max-w-[250px] mx-auto">
                {isCurrentPhase
                  ? "A background worker is generating this document..."
                  : "You must reach this phase to generate this artifact."}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Footer Actions */}
      {activeArtifact && (
        <div className="bg-card border-t px-6 py-4 flex flex-col gap-4">
          {isCurrentPhase && (
            <Textarea
              placeholder="Provide specific instructions to fix or change in the next generation..."
              className="resize-none overflow-hidden"
              rows={4}
              value={promptInput}
              onChange={(e) => setPromptInput(e.target.value)}
              disabled={isRegenerating}
            />
          )}

          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center">
              {isCurrentPhase ? (
                <Button
                  variant="outline"
                  onClick={handleRegenerate}
                  disabled={isRegenerating || !promptInput.trim()}
                >
                  {isRegenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RotateCcw className="w-4 h-4" />}
                  Regenerate
                </Button>
              ) : (
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div>
                        <Button
                          variant="outline"
                          disabled
                        >
                          <RotateCcw className="w-4 h-4" />
                          Regenerate
                        </Button>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>Can only regenerate artifacts for the current active ticket phase.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              )}
            </div>

            {activeArtifact.status === "draft" ? (
              <Button
                className="w-full sm:w-auto bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
                onClick={handleApprove}
              >
                <CheckCircle className="w-4 h-4" />
                Approve Document
              </Button>
            ) : (
              <Button
                variant="secondary"
                className="w-full sm:w-auto hover:bg-rose-100 hover:text-rose-700 transition-colors"
                onClick={handleUnapprove}
                disabled={!isCurrentPhase}
              >
                <XCircle className="w-4 h-4" />
                Revoke Approval
              </Button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
